decision_node:
  ros__parameters:
    # Wrench Controller Parameters
    k_surge: 1.0
    k_sway: 1.0
    k_yaw: 0.5
    motion_lowpass_alpha: 0.2

    # World Model Parameters
    max_velocity_clamp: 1.5
    perception_timeout_sec: 1.0
    velocity_decay: 0.95

    # Mission Parameters
    tree_xml_file: "config/trees.xml"
    main_tree_id: "QualificationMission" # Change to "FinalMission" for final

    # Camera switching hysteresis
    camera_switch_hysteresis: 0.5

    # Thresholds
    align_yaw_threshold: 0.1
    align_distance_threshold: 0.5
